import IISKursovaya_rabota_Borisova_AnnaКлиентEController from '../i-i-s-kursovaya-rabota-borisova-anna-клиент-e';

var IISKursovaya_rabota_Borisova_AnnaКлиентENewController = IISKursovaya_rabota_Borisova_AnnaКлиентEController;
export default IISKursovaya_rabota_Borisova_AnnaКлиентENewController;
