//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_rabota_Borisova_Anna
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Единицы.
    /// </summary>
    // *** Start programmer edit section *** (Единицы CustomAttributes)

    // *** End programmer edit section *** (Единицы CustomAttributes)
    public enum Единицы
    {
        
        // *** Start programmer edit section *** (Единицы.Мл CustomAttributes)

        // *** End programmer edit section *** (Единицы.Мл CustomAttributes)
        [Caption("Мл")]
        Мл,
        
        // *** Start programmer edit section *** (Единицы.Шт CustomAttributes)

        // *** End programmer edit section *** (Единицы.Шт CustomAttributes)
        [Caption("Шт")]
        Шт,
        
        // *** Start programmer edit section *** (Единицы.Грамм CustomAttributes)

        // *** End programmer edit section *** (Единицы.Грамм CustomAttributes)
        [Caption("Грамм")]
        Грамм,
        
        // *** Start programmer edit section *** (Единицы.Литров CustomAttributes)

        // *** End programmer edit section *** (Единицы.Литров CustomAttributes)
        [Caption("Литров")]
        Литров,
    }
}
