//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_rabota_Borisova_Anna
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудник.
    /// </summary>
    // *** Start programmer edit section *** (сотрудник CustomAttributes)

    // *** End programmer edit section *** (сотрудник CustomAttributes)
    [AutoAltered()]
    [Caption("Сотрудник")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("сотрудникE", new string[] {
            "ФИО as \'ФИО\'",
            "КодСотрудника as \'Код сотрудника\'",
            "ДатаРождения as \'Дата рождения\'",
            "НомерТелефона as \'Номер телефона\'",
            "Пол as \'Пол\'"})]
    [View("сотрудникL", new string[] {
            "ФИО as \'ФИО\'",
            "КодСотрудника as \'Код сотрудника\'",
            "ДатаРождения as \'Дата рождения\'",
            "НомерТелефона as \'Номер телефона\'",
            "Пол as \'Пол\'"})]
    public class сотрудник : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Kursovaya_rabota_Borisova_Anna.Пол fПол;
        
        private string fФИО;
        
        private int fКодСотрудника;
        
        private System.DateTime fДатаРождения;
        
        private int fНомерТелефона;
        
        private IIS.Kursovaya_rabota_Borisova_Anna.Должности fДолжности;
        
        // *** Start programmer edit section *** (сотрудник CustomMembers)

        // *** End programmer edit section *** (сотрудник CustomMembers)

        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (сотрудник.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.ДатаРождения Get start)

                // *** End programmer edit section *** (сотрудник.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (сотрудник.ДатаРождения Get end)

                // *** End programmer edit section *** (сотрудник.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.ДатаРождения Set start)

                // *** End programmer edit section *** (сотрудник.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (сотрудник.ДатаРождения Set end)

                // *** End programmer edit section *** (сотрудник.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// КодСотрудника.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.КодСотрудника CustomAttributes)

        // *** End programmer edit section *** (сотрудник.КодСотрудника CustomAttributes)
        public virtual int КодСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.КодСотрудника Get start)

                // *** End programmer edit section *** (сотрудник.КодСотрудника Get start)
                int result = this.fКодСотрудника;
                // *** Start programmer edit section *** (сотрудник.КодСотрудника Get end)

                // *** End programmer edit section *** (сотрудник.КодСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.КодСотрудника Set start)

                // *** End programmer edit section *** (сотрудник.КодСотрудника Set start)
                this.fКодСотрудника = value;
                // *** Start programmer edit section *** (сотрудник.КодСотрудника Set end)

                // *** End programmer edit section *** (сотрудник.КодСотрудника Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (сотрудник.НомерТелефона CustomAttributes)
        public virtual int НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.НомерТелефона Get start)

                // *** End programmer edit section *** (сотрудник.НомерТелефона Get start)
                int result = this.fНомерТелефона;
                // *** Start programmer edit section *** (сотрудник.НомерТелефона Get end)

                // *** End programmer edit section *** (сотрудник.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.НомерТелефона Set start)

                // *** End programmer edit section *** (сотрудник.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (сотрудник.НомерТелефона Set end)

                // *** End programmer edit section *** (сотрудник.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Пол.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.Пол CustomAttributes)

        // *** End programmer edit section *** (сотрудник.Пол CustomAttributes)
        public virtual IIS.Kursovaya_rabota_Borisova_Anna.Пол Пол
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.Пол Get start)

                // *** End programmer edit section *** (сотрудник.Пол Get start)
                IIS.Kursovaya_rabota_Borisova_Anna.Пол result = this.fПол;
                // *** Start programmer edit section *** (сотрудник.Пол Get end)

                // *** End programmer edit section *** (сотрудник.Пол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.Пол Set start)

                // *** End programmer edit section *** (сотрудник.Пол Set start)
                this.fПол = value;
                // *** Start programmer edit section *** (сотрудник.Пол Set end)

                // *** End programmer edit section *** (сотрудник.Пол Set end)
            }
        }
        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.ФИО CustomAttributes)

        // *** End programmer edit section *** (сотрудник.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.ФИО Get start)

                // *** End programmer edit section *** (сотрудник.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (сотрудник.ФИО Get end)

                // *** End programmer edit section *** (сотрудник.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.ФИО Set start)

                // *** End programmer edit section *** (сотрудник.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (сотрудник.ФИО Set end)

                // *** End programmer edit section *** (сотрудник.ФИО Set end)
            }
        }
        
        /// <summary>
        /// Сотрудник.
        /// </summary>
        // *** Start programmer edit section *** (сотрудник.Должности CustomAttributes)

        // *** End programmer edit section *** (сотрудник.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Kursovaya_rabota_Borisova_Anna.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (сотрудник.Должности Get start)

                // *** End programmer edit section *** (сотрудник.Должности Get start)
                IIS.Kursovaya_rabota_Borisova_Anna.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (сотрудник.Должности Get end)

                // *** End programmer edit section *** (сотрудник.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (сотрудник.Должности Set start)

                // *** End programmer edit section *** (сотрудник.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (сотрудник.Должности Set end)

                // *** End programmer edit section *** (сотрудник.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "сотрудникE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View сотрудникE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("сотрудникE", typeof(IIS.Kursovaya_rabota_Borisova_Anna.сотрудник));
                }
            }
            
            /// <summary>
            /// "сотрудникL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View сотрудникL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("сотрудникL", typeof(IIS.Kursovaya_rabota_Borisova_Anna.сотрудник));
                }
            }
        }
    }
}
